\contentsline {lstlisting}{\numberline {3.1}{\ignorespaces In diesem ,useEffect'-Hook werden nach der Zeit, welche sich hinter der Variable ,MINUTES\_MS' verbirgt, die Daten der API abgerufen, was \IeC {\"u}ber die Funktion in Zeile 3 geschieht. (Quelle: \cite {useIntervalCode})}}{9}{lstlisting.3.1}%
\contentsline {lstlisting}{\numberline {3.2}{\ignorespaces Ein Beispiel des Aufrufs eines Toasts aus der Datei ,DbConnectionService.ts'. (Quelle: Eigene Implementierung)}}{10}{lstlisting.3.2}%
\contentsline {lstlisting}{\numberline {3.3}{\ignorespaces Das Erstellen einer Datenbank mit Hilfe eines Beispiels der genutzten Expo-Bibliothek SQLite. (Quelle: \cite {sqlite})}}{17}{lstlisting.3.3}%
\contentsline {lstlisting}{\numberline {3.4}{\ignorespaces Dieser Code befindet sich vor der Definition des Eventhooks. Hier wird ein Array angelegt, welches Funktionen beinhaltet. Diese werden dann ab Zeile 11 im definierten Task abgearbeitet. (Quelle: Eigene Implementierung)}}{19}{lstlisting.3.4}%
\contentsline {lstlisting}{\numberline {3.5}{\ignorespaces Die verk\IeC {\"u}rzte Darstellung der Datei, welche die Daten der Parkm\IeC {\"o}glichkeiten beinhaltet. W\IeC {\"a}re Typensicherheit egal, k\IeC {\"o}nnten die Daten auch in eine JSON-Datei geschrieben werden. (Quelle: Eigene Implementierung)}}{22}{lstlisting.3.5}%
\contentsline {lstlisting}{\numberline {4.1}{\ignorespaces Diese Befehle m\IeC {\"u}ssen in die Kommandozeile eingegeben und anschlie\IeC {\ss }end ausgef\IeC {\"u}hrt werden, damit das Projekt verwendet werden kann. So werden die notwendigen Bibliotheken installiert.}}{24}{lstlisting.4.1}%
\contentsline {lstlisting}{\numberline {4.2}{\ignorespaces Um die Anwendung mit mit Android zu starten, sollte Android Studio heruntergeladen und installiert sein. Anschlie\IeC {\ss }end muss der passende Emulator \IeC {\"u}ber den Device Manager hinzugef\IeC {\"u}gt und gestartet werden. Danach werden diese Befehle in die Kommandozeile eingegeben und ausgef\IeC {\"u}hrt.}}{24}{lstlisting.4.2}%
\contentsline {lstlisting}{\numberline {4.3}{\ignorespaces Nachdem die ,Expo Go'-App im App-Store heruntergeladen wurde, kann mit der Ausf\IeC {\"u}hrung dieser Befehle in der Kommandozeile die Anwendung gestartet werden. Anschlie\IeC {\ss }end wird der nun in der Konsole angezeigte QR-Code mit der iPhone-Kamera gescannt. Dann \IeC {\"o}ffnet sich die Anwendung in der ,Expo Go'-App.}}{25}{lstlisting.4.3}%
\contentsline {lstlisting}{\numberline {A.1}{\ignorespaces Diese Funktion wird beim Betreten oder Verlassen eines Geofences ausgef\IeC {\"u}hrt. Im Fehlerfall bekommt der Nutzer per Toast mit, dass etwas schief gelaufen ist. Von Zeile 10 bis 17 wird sichergestellt, dass dasselbe Event nicht f\IeC {\"a}lschlicherweise mehrmals hintereinander auftritt. Anschlie\IeC {\ss }end werden die Werte, ob das Geofence verlassen oder betreten wird, gesetzt. Beim Eintritt in das Geofence wird der Nutzer mittels Toast informiert. (Quelle: Eigene Implementierung)}}{30}{lstlisting.A.1}%
